//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQCYCLER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pacote
    {
        public Pacote()
        {
            this.Comentario = new HashSet<Comentario>();
            this.PacoteRequisito = new HashSet<PacoteRequisito>();
        }
    
        public int id { get; set; }
        public Nullable<int> projetoId { get; set; }
        public string status { get; set; }
        public string NOME { get; set; }
    
        public virtual Projeto Projeto { get; set; }
        public virtual ICollection<Comentario> Comentario { get; set; }
        public virtual ICollection<PacoteRequisito> PacoteRequisito { get; set; }
    }
}
