//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQCYCLER
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjetoUsuario
    {
        public ProjetoUsuario()
        {
            this.FluxoAprovacaoProjeto = new HashSet<FluxoAprovacaoProjeto>();
        }
    
        public int id { get; set; }
        public Nullable<int> usuarioId { get; set; }
        public Nullable<int> projetoId { get; set; }
        public Nullable<int> papelUsuarioId { get; set; }
    
        public virtual ICollection<FluxoAprovacaoProjeto> FluxoAprovacaoProjeto { get; set; }
        public virtual PapelUsuario PapelUsuario { get; set; }
        public virtual Usuario Usuario { get; set; }
    }
}
