//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQCYCLER
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReqcyclerEntities : DbContext
    {
        public ReqcyclerEntities()
            : base("name=ReqcyclerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Area> Area { get; set; }
        public DbSet<ClassificacaoRequisito> ClassificacaoRequisito { get; set; }
        public DbSet<Comentario> Comentario { get; set; }
        public DbSet<FluxoAprovacaoProjeto> FluxoAprovacaoProjeto { get; set; }
        public DbSet<Pacote> Pacote { get; set; }
        public DbSet<PapelUsuario> PapelUsuario { get; set; }
        public DbSet<Projeto> Projeto { get; set; }
        public DbSet<ProjetoRequisito> ProjetoRequisito { get; set; }
        public DbSet<ProjetoUsuario> ProjetoUsuario { get; set; }
        public DbSet<Requisito> Requisito { get; set; }
        public DbSet<TipoUsuario> TipoUsuario { get; set; }
        public DbSet<Usuario> Usuario { get; set; }
    }
}
