//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQCYCLER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requisito
    {
        public Requisito()
        {
            this.ProjetoRequisito = new HashSet<ProjetoRequisito>();
        }
    
        public int id { get; set; }
        public Nullable<int> projetoId { get; set; }
        public Nullable<int> classificacaoRequisitoId { get; set; }
        public string nome { get; set; }
        public string tipoRequisito { get; set; }
        public Nullable<decimal> versaoSistema { get; set; }
        public string solicitante { get; set; }
        public string complexidade { get; set; }
        public string descricao { get; set; }
    
        public virtual ClassificacaoRequisito ClassificacaoRequisito { get; set; }
        public virtual ICollection<ProjetoRequisito> ProjetoRequisito { get; set; }
    }
}
