//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REQCYCLER
{
    using System;
    using System.Collections.Generic;
    
    public partial class Area
    {
        public Area()
        {
            this.Projeto = new HashSet<Projeto>();
        }
    
        public int id { get; set; }
        public string valor { get; set; }
    
        public virtual ICollection<Projeto> Projeto { get; set; }
    }
}
